name: Build & Deploy Image

on:
  push:
    branches: [main]
    paths-ignore:
      - 'deployment.yaml'

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
        # git clone https://github.com/hojekunle/insta-devops.git
        # cd your-repo
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate version tag (timestamp)
        id: tag
        run: echo "VERSION=$(date +'%Y-%m-%d-%H%M%S')" >> $GITHUB_ENV
        # VERSION=2025-12-11-143025
        # Image name: 
        # hojekunle/insta-devops-repo:2025-12-11-090512

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/insta-devops-repo:${{ env.VERSION }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/insta-devops-repo:${{ env.VERSION }}
